---

- name: Install required software
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - httpd
    - mysql-server
    - php
    - php-mysql
    - php-devel
    - php-gd
    - php-pecl-memcache
    - php-pspell
    - php-snmp
    - php-xmlrpc
    - MySQL-python

- pip:
    name: MySQL-python
